development:
  clients:
    default:
      database: soundly_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: soundly_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0

production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        connect_timeout: 15
